auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 10s
  wal:
    dir: loki/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: loki/index
  filesystem:
    directory: loki/chunks

limits_config:
  allow_structured_metadata: false
  reject_old_samples: false
  reject_old_samples_max_age: 8760h
  retention_period: 8760h
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  max_query_length: 8760h

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s